### ISSUE TITLE
IndexOutOfRangeException on Hololens build

### ISSUE THREAD

**Issue by bhtruong93** [KhronosGroup/UnityGLTF#99]
I'm getting this error trying to load a GLTF on the Hololens, but it seems to work perfectly in the editor.  I essentially copied the entire project into my existing Hololens project, which includes all the files in the plugin directory. Any ideas?

```
IndexOutOfRangeException: Index was outside the bounds of the array.
   at GLTF.Schema.Accessor.GetFloatElement(Byte[] buffer, Int32 byteOffset)
   at GLTF.Schema.Accessor.AsVector3Array(NumericArray& contents, Byte[] bufferData, Boolean normalizeIntValues)
   at GLTF.Schema.Accessor.AsVertexArray(NumericArray& contents, Byte[] bufferData)
   at GLTF.GLTFHelpers.BuildMeshAttributes(Dictionary`2& attributes)
   at UnityGLTF.GLTFSceneImporter.BuildMeshAttributes(MeshPrimitive primitive, Int32 meshID, Int32 primitiveIndex)
   at UnityGLTF.GLTFSceneImporter.CreateMeshPrimitive(MeshPrimitive primitive, Int32 meshID, Int32 primitiveIndex)
   at UnityGLTF.GLTFSceneImporter.CreateMeshObject(Mesh mesh, Transform parent, Int32 meshId)
   at UnityGLTF.GLTFSceneImporter.CreateNode(Node node)
   at UnityGLTF.GLTFSceneImporter.CreateNode(Node node)
   at UnityGLTF.GLTFSceneImporter.CreateScene(Scene scene)
   at UnityGLTF.GLTFSceneImporter.<ImportScene>d__23.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)
```

**Comment by bhtruong93** [comment]
Found out my problem, the URI that it was given wasn't completely escaped so it failed on the hololens. Funny that it still resolves in editor.
